### ISSUE TITLE
Test suite failed to run React native enzyme 

### ISSUE THREAD

**Issue by bhavinatharva** [QuickBlox/quickblox-react-native-sdk#66]
```
"react": "16.11.0",
"react-native": "0.61.3",
"quickblox-react-native-sdk": "^0.6.0-beta",
```

Test suite failed to run

TypeError: Cannot read properties of undefined (reading 'addListener')

```
 import QB from "quickblox-react-native-sdk";
```

```
at Object.<anonymous> (../../../node_modules/quickblox-react-native-sdk/index.js:651:21)
```

**Comment by VladimirNybozhinsky** [comment]
@[bhavinatharva](https://github.com/bhavinatharva) Hi [bhavinatharva](https://github.com/bhavinatharva),
This is Vladimir from QuickBlox.
To help us with your case we request the following points:
1. Update npm packages.
2. Update QB RN SDK to the latest version.
3. Update [enzyme](https://www.npmjs.com/package/@wojtekmaj/enzyme-adapter-react-17) module for your React native version.
4. Describe all steps to reproduce the problem
5. Try to run our samples which are [here](https://github.com/QuickBlox/quickblox-react-native-samples)
6. Provide us with Logs

**Comment by bhavinatharva** [comment]
Hello @VladimirNybozhinsky 

Thank you for your response.
I will look into that and will inform here if I get any update on test cases.

**Comment by bhavinatharva** [comment]
Hello @VladimirNybozhinsky 

I did update sdk with this
```
info Fetching system and libraries information...
System:
    OS: macOS 12.6.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 607.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - ~/Workspace/blushbrush-ide/src/node_modules/.bin/npm
    Watchman: 2023.07.10.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild

"quickblox-react-native-sdk": "^0.9.4",
```

but getting same 

```
 Cannot read properties of undefined (reading 'addListener')
 at Object.<anonymous> (../../../node_modules/quickblox-react-native-sdk/index.js:617:21)
 ```

**Comment by VladimirNybozhinsky** [comment]
Hello @bhavinatharva, 
Thanks for the info!
Have you tried running our samples? do they work for you?

**Comment by VladimirNybozhinsky** [comment]
Hello @bhavinatharva !
Quickblox has recently created a [Discord community](https://discord.com/invite/ZWZ3WpYZ9q), feel free to join! We have created thematic channels where you can ask all questions to our developers.

**Comment by VladimirNybozhinsky** [comment]
@[bhavinatharva](https://github.com/bhavinatharva)  Hi [bhavinatharva](https://github.com/bhavinatharva),

1.  Check out our [React Native Documentation](https://docs.quickblox.com/docs/react-native-quick-start)
2.  If this doesn't work, please provide your steps and code

**Comment by quickblox-custom-development** [comment]
@bhavinatharva Hi! Please let us know whether you still experience the reported issue.
If we correctly understand from the provided info, you tried to create tests for something.
If yes, the QB React Native library uses native modules which may cause issues for a library you use for tests.
You may first need to mock the library.
