### ISSUE TITLE
App crash in release build  

### ISSUE THREAD

**Issue by Kundannetset** [QuickBlox/quickblox-react-native-sdk#69]
java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@51ce6d91: getName
at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
at android.os.Parcel.createException(Parcel.java:2995)
at android.os.Parcel.readException(Parcel.java:2978)
at android.os.Parcel.readException(Parcel.java:2920)
at android.bluetooth.IBluetoothManager$Stub$Proxy.getName(IBluetoothManager.java:552)
at android.bluetooth.BluetoothAdapter.getName(BluetoothAdapter.java:1562)
at com.quickblox.reactnative.webrtc.QBAudioManager$QBBluetoothManager.logBluetoothAdapterInfo(QBAudioManager.java:839)
at com.quickblox.reactnative.webrtc.QBAudioManager$QBBluetoothManager.start(QBAudioManager.java:720)
at com.quickblox.reactnative.webrtc.QBAudioManager.start(QBAudioManager.java:193)
at com.quickblox.reactnative.webrtc.WebRTCCallService.initAudioManager(WebRTCCallService.java:299)
at com.quickblox.reactnative.webrtc.WebRTCCallService.access$1000(WebRTCCallService.java:64)
at com.quickblox.reactnative.webrtc.WebRTCCallService$SessionConnectionListener.onStateChanged(WebRTCCallService.java:724)
at com.quickblox.reactnative.webrtc.WebRTCCallService$SessionConnectionListener.onStateChanged(WebRTCCallService.java:679)
at com.quickblox.videochat.webrtc.BaseSession$1.run(BaseSession.java:239)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8232)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.bluetooth.BluetoothManagerService.checkPermissionForDataDelivery(BluetoothManagerService.java:3941)
at com.android.server.bluetooth.BluetoothManagerService.checkConnectPermissionForDataDelivery(BluetoothManagerService.java:3959)
at com.android.server.bluetooth.BluetoothManagerService.getName(BluetoothManagerService.java:2449)
at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:256)
at android.os.Binder.execTransactInternal(Binder.java:1285)

**Comment by IlliaChemolosov** [comment]
@kundannetsetDemo 
We are in the process of updating all dependencies in the samples. The samples will be made available once all testing stages are successfully completed.

**Comment by QB-maksym-pidhorbunskyi** [comment]
Hello @kundannetsetDemo 
This is Maksym from QuickBlox support.
Could you provide the following details to investigate the issue:
1. What version of Android OS does the problem occur on?
2. Which SDK version are you using?
Please make sure that you use the latest version of React Native: https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.9.4
3. What are the steps to reproduce on our side?
4. Did you get this issue in your app code or QuickBlox samples? What QuickBox sample do you use - chat or video calling? 
5. Please try to reproduce the issue on our samples in order to understand if the issue is related to the client-side implementation or server-side performance:
Chat sample: https://docs.quickblox.com/docs/code-samples#chat-samples
Video calling sample: https://docs.quickblox.com/docs/code-samples#video-calling-samples
6. React Native version.
Information from react-native info.
Information from npm list.

Looking forward to your reply with the requested details.
